### PR TITLE
Make duplicate namespace nodes not fatal

### PR DESCRIPTION
**Pull request by Dennisbonke**
This allows my machine to proceed further into booting while trying out managarm. It then runs into issue #87 so I'm unable to verify that this solves my problem. I checked that it doesn't break in qemu.

### CODE REVIEW

**Comment by thomtl** [comment]
We should probably also remove the duplicate node from the main list, and instead of `continue`ing, `break`

**Comment by rizet** [comment]
I'd rather believe that ignoring the issue is the wrong course of action here, instead of resolving it outright.

**Comment by AtieP** [comment]
> I'd rather believe that ignoring the issue is the wrong course of action here, instead of resolving it outright.

The problem is that many firmware developers generate straight broken AML code, and the interpreter should generally work everywhere

**Comment by rizet** [comment]
> > I'd rather believe that ignoring the issue is the wrong course of action here, instead of resolving it outright.
> 
> The problem is that many firmware developers generate straight broken AML code, and the interpreter should generally work everywhere

I meant making the namespace nodes not fatal, and adding them to the list, instead of just ignoring the namespace nodes or trying to resolve them, is a sub-par fix. I agree with thom's comment.

**Comment by thomtl** [comment]
Refer to #114

**Comment by austanss** [comment]
It's hard for me to remain on this website when I witness myself making half-baked opinions on issues that I have no pertaining to.

**Pull request closed without merging**
